include:
  - project: 'crd1/tpam-ci-cd'
    ref: dev
    file: '/tpam-ci.yml'

variables:
  MVN_PROJECT_VERSION_PROPERTY: nextcloud-api

stages:
  - test
  - downstream
  - deploy
  - sonar
  - triggers-services

# ------------------------------------- TRIGGERS ---------------------------------------------------
tpam-fts-client:
  extends: .trigger_template
  stage: triggers-services
