include:
  - project: 'crd1/tpam-ci-cd'
    ref: dev
    file: '/tpam-ci.yml'

variables:
  MVN_PROJECT_VERSION_PROPERTY: nextcloud-api

stages:
  - test
  - downstream
  - deploy
  - sonar
  - triggers-services

Dependency Check:
  stage: test
  allow_failure: true
  tags:
    - build
  script:
    - echo "Not implemented for nextcloud-api"

Sonarqube Analysis:
  stage: sonar
  allow_failure: true
  tags:
    - build
  script:
    - echo "Not implemented for nextcloud-api"
# ------------------------------------- TRIGGERS ---------------------------------------------------
tpam-fts-client:
  extends: .trigger_template
  stage: triggers-services
